### ISSUE TITLE
Models: Define relationships

### ISSUE THREAD

**Issue by jcpickens0215** [lelandcypress/S.W.O.R.D#2]
Define the relationships between user_auth, characters, and missions

**Comment by lelandcypress** [comment]
See Pull Request.

**Comment by lelandcypress** [comment]
I looked up the Sequalize Documentation, and conducted a little trial and error. I refactored the code to reflect the following relations.

Users => Hero (One to One)
Hero => Mission (One to many. Specifically one mission per hero, but Mission can have multiple Heros.)
